sources:
  - name: raw
    description: Raw Bronze-layer tables loaded via Airflow from CSV files
    database: postgres
    schema: bronze

    tables:
      - name: airbnb_raw      

      - name: lga_code_raw
        
      - name: lga_g01_raw
      
      - name: lga_g02_raw
        
      - name: lga_suburb_raw
       
